### PR TITLE
Update branch to Netflix/bless master

### PR DESCRIPTION
**Pull request by russell-lewis**
Catching your PR up on all the other activity over the last few days.

### CODE REVIEW

**Comment by pecigonzalo** [comment]
@russell-lewis I think it might be simpler to rebase my changes, would you be interested in adding again the Pipenv parts or should I keep that separate?

The handler part is only e365216.

**Comment by russell-lewis** [comment]
I don't have objections to moving to Pipenv, I don't have any first hand experience moving to it yet. It looks pretty reasonable, and the improved locking is a nice property.  Instead of me trying to get it working cleanly in your branch, I just dropped the changes so that I could build, deploy, and test the updated code.

**Comment by pecigonzalo** [comment]
I'll update make it workable and update the PR, tonight. Thanks.

**Comment by russell-lewis** [comment]
I don't have any objections to you rebasing and updating your main PR instead if you find that easier for you.  I hope this merge commit saves you a bunch of time catching up on the other features that just went in to the master.

**Pull request merged**
